content_creator/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include ('contents.urls')),
    path('users/',include ('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contents/urls.py
"""deinfing urls for contents app"""

from django.urls import path
from . import views

app_name = 'contents'

urlpatterns = [
	#Home page
	path('', views.index, name='index'),
	path('imptopics/', views.imptopics, name='imptopics'),
	path('imptopics/<int:topic_id>/', views.imptopic, name='imptopic'),
	path('new_topic/', views.new_topic, name='new_topic'),
	path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
	path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
	path('edit_topic/<int:topic_id>/', views.edit_topic, name='edit_topic'),

]

users/urls.py
"""Define urls for users app"""

from django.urls import path, include

from. import views

app_name = "users"

urlpatterns = [
	#includes defaulth auth urls
	path('', include('django.contrib.auth.urls')),
	#Registration page url
	path('register/', views.register, name='register'),

]

contents/models.py
from django.db import models
from django.db.models import JSONField
from django.contrib.auth.models import User
# Create your models here.

keys = (
	('a', 'A'),
	('a#', 'A#'),
	('b', 'B'),
	('c', 'C'), 
	('c#', 'C#'),
	('d', 'D'),
	('d#', 'D#'),
	('e', 'E'),
	('f', 'F'),
	('f#', 'F#'),
	('g', 'G'),
	('g#', 'G#'), 
)


scales = (
	('major', 'Major'),
	('minor', 'Minor'),
	('melodic', 'Melodic'),
	('harmonic', 'Harmonic'),  
)

class ImprovisationTopic(models.Model):
	"""This title of content of one song post for improvisation """

	title = models.CharField(max_length=500)
	key = models.CharField(max_length=500, choices=keys, default='C Major')
	scale = models.CharField(max_length=500, choices=scales, default='Major')
	chords = JSONField()
	date_added = models.DateTimeField(auto_now_add=True)
	owner = models.ForeignKey(User, on_delete=models.CASCADE)

	def __str__(self):
		"""Return string representation of the model"""
		return self.title


class ImprovisationEntry(models.Model):
	"""The content of each song improvisation post"""

	topic = models.ForeignKey(ImprovisationTopic, on_delete=models.CASCADE)
	text = models.TextField()
	date_added = models.DateTimeField(auto_now_add=True)

	class Meta:
		verbose_name_plural = 'Improvisation entries'

	def __str__(self):
		"""Return a string representation of the model."""
		#if len(self.text) < 50:
		return self.text
		#else:
		#	return self.text[:50] + "..."



class Fretboard(models.Model):
	"""the collection of images from fretboardgtr"""
	name = models.CharField(max_length=500)
	dominant = models.ImageField(blank=True, upload_to="media")
	dominant4 = models.ImageField(blank=True, upload_to="media")
	frets = models.ImageField(blank=True, upload_to="media")
	pentatonic = models.ImageField(blank=True, upload_to="media")	
	def __str__(self):
		"""Return string representation of the model"""
		return self.name

contents/forms.py
from django import forms

from .models import ImprovisationTopic as it, ImprovisationEntry as ie


class ImprovisationTopicForm (forms.ModelForm):

	class Meta:

		model = it

		fields = ['title', 'key','scale','chords']
		labels = {'title': 'Title', 'key': 'Key', 'scale':'Scale','chords':'Chords'}

	def __init__(self, *args, **kwargs):

		super().__init__(*args, **kwargs)
		self.fields['title'].initial = "Improvising to"
		self.fields['chords'].initial = {'Chords':['','']}


class ImprovisationEntryForm (forms.ModelForm):

	class Meta:

		model = ie

		fields = ['text']
		labels = {'text': ''}
		widgets = {'text': forms.Textarea(attrs={'cols':80})}

contents/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.http import Http404
from . fret import fretboard, fretboardDominant, fretboardDom4, minorpentatonic
from . scale_generator import scale_generator

from . models import ImprovisationTopic as it, ImprovisationEntry as ie, Fretboard as ft
from .forms import ImprovisationTopicForm as itf, ImprovisationEntryForm as ief

# Create your views here.

def index(request):

	return render(request, 'contents/index.html')


@login_required
def imptopics(request):
	"""To show the list of all topics"""

	topics = it.objects.filter(owner=request.user).order_by('date_added') #get the list of topics for current user
	context = {'topics':topics}

	return render (request, 'contents/imptopics.html', context)

@login_required
def imptopic(request, topic_id):
	"""Shows topic details with its entries"""

	

	topic = it.objects.get(id=topic_id)

	#Getting chords in the right format fom JSON format
	chord_set = topic.chords
	chord = chord_set["Chords"]
	chording = ' - '.join(chord)

	#Generating pattern, notes and scale notes
	if topic.scale.title() == 'Minor':
		pattern, scale, notes, dominant, dom4, pentatonic = scale_generator(topic.key,topic.scale)
	else:
		pattern, scale, notes, dominant, dom4 = scale_generator(topic.key,topic.scale)

	scales = ' - '.join(scale)

	#creating and saving fretboard scale images in Fretboard class

	all_frets = ft.objects.all()
	fret_names = [] #creatiing set to get all objects already created for a particular key

	for frs in all_frets:
		fret_names.append(frs.name) #putting al scale names in a set to check if that has already been created

	if f"{topic.key.title()} {topic.scale.title()}" not in fret_names: #only create images if the images have already NOT been created. If already created, use the same. 

		fretty = ft() #creating an object of the fretboard class

		fretty.name = f"{topic.key.title()} {topic.scale.title()}" #setting name of the object to be key attribute of the topic which is a drop down select
		#creating the images for dom, dom4 and all
		fretboardDominant(topic.key,topic.scale)
		fretboardDom4(topic.key,topic.scale)
		fretboard(topic.key,topic.scale)
		if topic.scale.title() == 'Minor':
			minorpentatonic(topic.key,topic.scale)
		#ft.name=f"{topic.key.title()} {topic.scale.title()}" #setting name of the database entry to the the key name and scale

		#storing above created images in class attributes
		fretty.dominant = f'media/{topic.key.title()} {topic.scale.title()} Dominants.JPG' 
		fretty.dominant4 = f'media/{topic.key.title()} {topic.scale.title()} Dominants and 4th.JPG'
		fretty.frets = f'media/{topic.key.title()} {topic.scale.title()}.JPG'
		fretty.pentatonic = f'media/{topic.key.title()} {topic.scale.title()} pentatonic.JPG'

		fretty.save() #saving the new instance of the object into the database
	
	fretboards = ft.objects.filter(name=f"{topic.key.title()} {topic.scale.title()}")

	if request.user != topic.owner:
		raise Http404
	entries = topic.improvisationentry_set.all().order_by('date_added')
	context = {'topic':topic, 'entries': entries, 'pattern':pattern, 'scales':scales, 'notes': notes,'chording':chording,'dominantimg':'dominantimg','fretboards':fretboards}

	return render (request, 'contents/imptopic.html', context)


@login_required
def new_topic(request):
	"""Adding a new topic for improivsation"""

	if request.method != 'POST':
		"""if they are not posting or submitting the data"""
		form = itf() #show a blank form
	else:
		form = itf(data=request.POST)
		if form.is_valid():
			new_topic = form.save(commit=False)
			new_topic.owner = request.user
			new_topic.save()
			return redirect('contents:imptopics')

	#Display a blank invalid form	
	context = {'form':form}

	return render(request, 'contents/new_topic.html', context)



@login_required
def edit_topic(request, topic_id):

	topic = it.objects.get(id=topic_id)

	if topic.owner != request.user:
		raise Http404

	if request.method != 'POST':
		form = itf(instance=topic)
	else:
		form = itf(instance=topic, data=request.POST)
		if form.is_valid():
			form.save()
			return redirect('contents:imptopic', topic_id=topic.id)

	context = {'topic':topic, 'form': form}

	return render(request, 'contents/edit_topic.html', context)

@login_required
def new_entry(request, topic_id):

	topic = it.objects.get(id=topic_id)

	if request.method != 'POST':
		form =ief()
	else:
		form = ief(data=request.POST)
		if form.is_valid():
			new_entry = form.save(commit=False)
			new_entry.topic = topic
			new_entry.save()
			return redirect('contents:imptopic', topic_id=topic_id)

	context = {'topic':topic, 'form': form}

	return render(request, 'contents/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):

	entry = ie.objects.get(id=entry_id)
	topic = entry.topic

	if topic.owner != request.user:
		raise Http404

	if request.method != 'POST':
		form = ief(instance=entry)
	else:
		form = ief(instance=entry, data=request.POST)
		if form.is_valid():
			form.save()
			return redirect('contents:imptopic', topic_id=topic.id)

	context = {'entry':entry, 'topic':topic, 'form': form}

	return render(request, 'contents/edit_entry.html', context)

contents/templates/contents/base.html
{% load bootstrap4 %}

<!doctype html> 
<html lang="en"> 
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1,
  shrink-to-fit=no"> 
  <title>MH - Content Creator </title>
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

</head>
<body>

<nav class="navbar navbar-expand-lg bg-light">
    <a class="navbar-brand" href="{% url 'contents:index' %}"> MH - Content Creator </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  	<div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'contents:imptopics' %}">Improvisation Topics</a>
        </li>
      </ul>
<!-- <a href="{% url 'contents:index' %}"> Home </a> -  -->
<!-- <a href="{% url 'contents:imptopics' %}"> Improvisation Topics </a> -  -->
     <ul class="navbar-nav ml-auto">
		{% if user.is_authenticated %}
		<li class="nav-item">
		<span class="navbar-text">Hello, {{ user.username }}.</span>
		</li>
		<li class="nav-item">
			<a class="nav-link" href=" {% url 'users:logout' %}">Log Out</a>
		</li>
<!-- <p> Hello {{ user.username }}</p> - <a href=" {% url 'users:logout' %}">Log Out </a> -->

		{% else %}
		<li class="nav-item">
			<a class="nav-link" href="{% url 'users:login' %}"> Log In </a>
		</li>
		<li class="nav-item">
			<a class="nav-link" href="{% url 'users:register' %}"> Register </a>
		</li>
		{% endif %}
		<!-- <a href="{% url 'users:login' %}"> Log In </a> - <a href="{% url 'users:register' %}"> Register </a> -->
	</ul>
	</div>
</nav>	
<main role="main" class="container"> 
	<div class="pb-2 mb-2 border-bottom">

		{% block page_header %}{% endblock page_header %} </div>
	<div>
		{% block content %}{% endblock content %}
	</div> 
</main>
</body>
</html>

contents/templates/contents/edit_entry.html
{% extends "contents/base.html" %}

{% block content%}

<p> Editing entry for <a href="{% url 'contents:imptopic' topic.id %}">{{ topic }} </a></p>

<form action="{% url 'contents:edit_entry' entry.id %}" method='POST'>
	{% csrf_token %}
	{{ form.as_p }}
	<button name='submit'>Save Changes</button>
</form>

{% endblock content%}

contents/templates/contents/edit_topic.html
{% extends "contents/base.html" %}

{% load bootstrap4 %}

{% block page_header %}
<h2> Edit Improvisation Topics</h2>
{% endblock page_header %}


{% block content%}

<p> Editing <a href="{% url 'contents:imptopic' topic.id %}">{{ topic }} </a></p>

<form action="{% url 'contents:edit_topic' topic.id %}" method='POST'>
	{% csrf_token %}
	{{ form.as_p }}
	<button name='submit'>Save Changes</button>
</form>

{% endblock content%}

contents/templates/contents/imptopic.html
{% extends "contents/base.html" %}


{% block content %} 


<h2>Topic - {{ topic }} </h2>
<!-- <a href="{% url 'contents:new_entry' topic.id %}">Add New Entry</a>

<ul>
	{% for entry in entries %}
	<li> {{ entry }} </li> - <a href="{% url 'contents:edit_entry' entry.id %}"> Edit </a>
	{% empty %}

	<p> No improvisation entries have been added yet </p>

	{% endfor %}

</ul> -->

<p>How to improvise to this song? The things we need to start off are: </p>

<ul>
<li>What the key of the song is?</li>
<li>What are the notes in the key’s scale?</li>
<li>Where these notes are in a guitar?</li>
</ul>

<p>For this song, the answers would be:</p>

<h1>What is the key of the song?</h1>

<p>The song is in the key of {{ topic.key | title }} {{ topic.scale | title }}.</p>

<h1>What are the notes in the key’s scale?</h1>

<p>To find the notes in a {{ topic.scale | title }} scale we put the root note (in this case ‘{{ topic.key | title }}' note) in the key and follow the W-H pattern for {{ topic.scale | title }} scale which goes: {{ pattern }}</p>

<h2>{{ notes }}</h2>

<h2>{{ scales }}</h2>

<p>Once you have the key of the song, the notes that sounds most harmonic, in other words, beautiful with that song's chords are the root (the key note), the third and the fifth.</p>

<p>For {{ topic.key | title }} {{ topic.scale | title }}, one of the places you can find the Root, third and fifth is</p>

{% for f in fretboards%}
<img src="{{ f.dominant.url }}" alt="img">
{% endfor %}


<p>Just play the backing track  which has the same chords as the song:</p>

<h3>{{ chording }}</h3>

<p>Or you can find the karaoke version of the song in youtube and use it as a baking track. Try to play the notes above with the track. See how it feels. Once you hear the "dominance" of the root, third and fifth. We can try to add the fourth note to the improvisation. </p>

<p>You can find the fourth notes added below</p>

{% for f in fretboards%}
<img src="{{ f.dominant4.url }}" alt="img">
{% endfor %}


<p>Try playing around the backing track with these notes. See how you can feel the difference of root, third and fifth and how fourth tries to create "tension" but still feels like it gets in there somewhere. If you feel like you cannot fit in the fourth, play the fourth less frequently. </p>

<p>Once you feel where the fourth fits in, try to add more of the notes in the scale.</p>

<p>Lets looks at all the notes in the scale.</p>

{% for f in fretboards%}
<img src="{{ f.frets.url }}" alt="img">
{% endfor %}

<p>Try playing around with all the notes you see above. If you feel like you are not playing to you liking or the notes are not fitting in, go back up to just the notes with root, third, fourth and fifth. Play just those notes for a while. See if you can slowly add one new note at a time. </p>

{% for f in fretboards%}
  {% if f.pentatonic %}
    <img src="{{ f.pentatonic.url }}" alt="img">
  {% endif %}
{% endfor %}

{% endblock content %}

contents/templates/contents/imptopics.html
{% extends "contents/base.html" %}

{% load bootstrap4 %}

{% block page_header %}
<h2> Improvisation Topics</h2>
{% endblock page_header %}

{% block content %} 



<h3><a href= "{% url 'contents:new_topic' %}">Add New Topic</a></h3>
<ul>{% for topic in topics %}
	<li>
		<h3><a href= "{% url 'contents:imptopic' topic.id %}">{{ topic }} </a>
	    </h3> - <a href="{% url 'contents:edit_topic' topic.id %}"> Edit </a>

	</li>
	{% empty %}

	<p><h3> No improvisation topics have been added yet </h3></p>

	{% endfor %}

</ul>

{% endblock content %}

contents/templates/contents/index.html
{% extends "contents/base.html" %}

{% block page_header %}

<div class="jumbotron">
 <h1 class="display-3">MH Content Creator</h1>
  <p class="lead">Beginning of the content creation tool is here. Simplyfy the way you can create content and generate great contents within a shoter period of time</p>

{% if user.isnot_authenticated %}
<a class="btn btn-lg btn-primary" href="{% url 'users:register' %}" role="button">Register &raquo;</a>
{% endif %}
</div>
{% endblock page_header %}
{% block content %} 

{% endblock content %}

contents/templates/contents/logged_out.html
{% extends "contents/base.html" %}

{% block content %}
<p> You have been logged out </p>
{% endblock content %}

contents/templates/contents/new_entry.html
{% extends "contents/base.html" %}

{% block content%}

<p> Adding a new entry for <a href="{% url 'contents:imptopic' topic.id %}">{{ topic }} </a></p>

<form action="{% url 'contents:new_entry' topic.id %}" method='POST'>
	{% csrf_token %}
	{{ form.as_p }}
	<button name='submit'>Add Entry</button>
</form>

{% endblock content%}

contents/templates/contents/new_topic.html
{% extends "contents/base.html" %}

{% load bootstrap4 %}

{% block page_header%}
<h2> Adding a new improvisation post </h2>
{% endblock page_header%}


{% block content%}


<form action="{% url 'contents:new_topic' %}" method='POST'>
	{% csrf_token %}
	{% bootstrap_form form %}

	{% buttons %}
	<button name='submit'>Add topic</button>
	{% endbuttons %}

</form>

{% endblock content%}